// GitHub holds the shared snapshot; IndexedDB remains the offline working copy.
export const SNAPSHOT_URL='https://github.com/SamHMews/PPLUL/blob/main/data/workouts.json';
const API='https://api.github.com/repos/SamHMews/PPLUL/contents/data/workouts.json';
export function trainingSignature(state){const s=structuredClone(state);delete s.revision;delete s.view;for(const w of [s.active,...s.archives])for(const day of Object.values(w.days))delete day.current;return JSON.stringify(s);}
export const encodeSnapshot=s=>{const bytes=new TextEncoder().encode(JSON.stringify(s));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
export const decodeSnapshot=s=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0))));
export function createGitHubSync({getState,notify,fetcher=fetch,session=sessionStorage,local=localStorage}){
 let token=local.getItem('training-github-token')||session.getItem('training-github-token')||'',sha=null,ready=false,busy=false,pending=false,timer,remote=null;
 if(token){local.setItem('training-github-token',token);session.removeItem('training-github-token');}
 const status=text=>notify(text);
 async function request(method,body){const r=await fetcher(API+(method==='GET'?'?ref=main':''),{method,cache:'no-store',headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(method==='GET'&&r.status===404)return null;if(!r.ok){const e=new Error(r.status===409||r.status===422?'GitHub has changed. Reconnect to compare copies before saving.':r.status===401||r.status===403?'GitHub access failed. Check your token and repository permissions.':'GitHub save failed. Your device copy is safe; try again.');e.conflict=r.status===409||r.status===422;throw e;}return r.json();}
 async function connect(value=token){if(busy)throw new Error('A GitHub save is still finishing. Try again.');token=value?.trim()||token;ready=false;if(!token)throw new Error('Enter a GitHub token.');local.setItem('training-github-token',token);session.removeItem('training-github-token');status('Checking GitHub…');const file=await request('GET');remote=file?decodeSnapshot(file.content):null;sha=file?.sha||null;const baseline=JSON.parse(local.getItem('training-github-baseline')||'null');if(remote&&trainingSignature(remote)!==trainingSignature(getState())&&sha!==baseline?.sha){status('Choose which copy to continue with.');return remote;}ready=true;await flush();return null;}
 async function flush(){clearTimeout(timer);if(!ready||!token)return;if(busy){pending=true;return;}const snapshot=structuredClone(getState()),signature=trainingSignature(snapshot),baseline=JSON.parse(local.getItem('training-github-baseline')||'null');if(baseline?.sha===sha&&baseline?.signature===signature){status('Saved to GitHub');return;}busy=true;pending=false;status('Saving to GitHub…');try{const r=await request('PUT',{message:'Save workout history',branch:'main',content:encodeSnapshot(snapshot),...(sha?{sha}:{})});sha=r.content.sha;local.setItem('training-github-baseline',JSON.stringify({sha,signature}));status('Saved to GitHub');}catch(e){if(e.conflict)ready=false;status(e.message);throw e;}finally{busy=false;if(pending&&ready){pending=false;schedule();}}}
 function schedule(){if(!ready)return;status('Changes waiting to save');clearTimeout(timer);timer=setTimeout(()=>flush().catch(()=>{}),1500);}
 async function chooseRemote(){if(!remote)throw new Error('No GitHub copy available.');local.setItem('training-github-baseline',JSON.stringify({sha,signature:trainingSignature(remote)}));ready=true;remote=null;await flush();}
 async function chooseLocal(){ready=true;remote=null;await flush();}
 function disconnect(){if(busy)throw new Error('A GitHub save is still finishing. Try again.');clearTimeout(timer);ready=false;token='';local.removeItem('training-github-token');session.removeItem('training-github-token');status('GitHub disconnected. Workouts are saved on this device.');}
 return {connect,flush,schedule,chooseRemote,chooseLocal,disconnect,hasToken:()=>!!token};
}
