export const DAYS=['Push','Pull','Legs','Upper','Lower'];
const ex=(id,name,sets,target,unit='total weight',increment=null,variants=null)=>({id,name,sets,target,unit,increment,variants});
export const ROUTINES={
Push:[ex('bench','Bench Press',2,'4–5'),ex('incline-db','Incline Dumbbell Press',2,'7–9','per dumbbell',2.5),ex('fly','Cable Flyes',2,'7–9','machine weight'),ex('dips','Dips',2,'7–9','choose weight type',null,['Bodyweight','Added weight','Assisted']),ex('shoulder-db','Dumbbell Shoulder Press',2,'7–9','per dumbbell',2.5),ex('lateral','Lateral Raises',2,'8–12','choose weight type'),ex('skull','Skullcrushers',2,'7–9','choose weight type'),ex('pushdown','Tricep Pushdown',2,'10–12','machine weight')],
Pull:[ex('mag-pulldown','MAG Grip Lat Pulldowns',2,'7–9','machine weight'),ex('smith-row','Smith Machine Row',3,'5–7'),ex('wide-db-row','Chest-Supported Dumbbell Rows (Wide Pull, 45°)',3,'7–9','per dumbbell',2.5),ex('face-pull','Face Pulls (Two Ropes)',2,'7–9','machine weight'),ex('incline-curl','Incline Curls',2,'7–9','per dumbbell',2.5),ex('preacher','Preacher Curls',2,'5–7','choose weight type'),ex('hammer-cable','Hammer Cable Curls',2,'5–7','machine weight'),ex('reverse-ez','Reverse EZ Bar Curls',4,'8–12')],
Legs:[ex('squat','Squats',3,'4–6'),ex('ham-curl','Hamstring Curls',2,'8–10','machine weight'),ex('leg-extension','Leg Extensions',2,'10–12','machine weight'),ex('abductor','Hip Abductors',2,'12–15','machine weight'),ex('calf','Calf Raises',2,'12–15','choose weight type')],
Upper:[ex('lat-upper','Lat Pulldown',2,'5–7','machine weight'),ex('incline-db','Incline Dumbbell Press',2,'7–9','per dumbbell',2.5),ex('upper-row','Barbell or Chest-Supported Row',2,'5–7','choose weight type',null,['Barbell Row','Chest-Supported Row']),ex('upper-press','Overhead Barbell or Dumbbell Press',2,'4–6','choose weight type',null,['Overhead Barbell Press','Overhead Dumbbell Press']),ex('lateral','Lateral Raises',2,'10–12','choose weight type'),ex('upper-curl','Barbell or Cable Curl',2,'8–10','choose weight type',null,['Barbell Curl','Cable Curl']),ex('pushdown','Tricep Pushdown',2,'8–10','machine weight')],
Lower:[ex('deadlift','Deadlift (Barbell or Trap Bar)',2,'3–5','total weight',null,['Barbell Deadlift','Trap Bar Deadlift']),ex('bulgarian','Bulgarian Split Squats',2,'6–8 per leg','choose weight type'),ex('ham-curl','Hamstring Curls',2,'8–10','machine weight'),ex('hip-thrust','Hip Thrusts',2,'6–8'),ex('leg-extension','Leg Extensions',2,'10–12','machine weight'),ex('calf','Calf Raises',2,'12–15','choose weight type'),ex('abs','Hanging Leg Raises or Cable Crunches',2,'12–15','choose weight type',null,['Hanging Leg Raises','Cable Crunches'])]};
export const SEED=[['Push','bench',80,8,2,'reported','exact','total weight'],['Push','incline-db',30,12,2,'routine_inferred','exact','per dumbbell'],['Push','shoulder-db',25,11,2,'reported','exact','per dumbbell'],['Pull','mag-pulldown',20.5,8,2,'reported','exact','machine weight'],['Pull','smith-row',90,6,3,'reported','estimated','total weight'],['Pull','face-pull',23.7,9,2,'reported','exact','machine weight']].map(([day,id,weight,reps,sets,sets_source,precision,unit])=>({day,id,weight,reps,sets,sets_source,precision,unit,date:null,source:'user_reported',variant:null,effort:null}));
export function createWeek(number,settings={}){return {id:crypto.randomUUID(),number,startedAt:new Date().toISOString(),archivedAt:null,bonus:false,days:Object.fromEntries(DAYS.map(day=>[day,{current:ROUTINES[day][0].id,entries:ROUTINES[day].map(e=>({...structuredClone(e),...settings[day+':'+e.id],completed:false,completedAt:null,weight:null,reps:null,effort:null,precision:'exact',variant:null}))}]))};}
export function initialState(){return {schema:1,revision:0,active:createWeek(1),archives:[],seed:structuredClone(SEED),settings:{},view:{page:'home',day:null}};}
export const remaining=(session)=>session.entries.filter(e=>!e.completed);
export function currentEntry(session){return remaining(session).find(e=>e.id===session.current)||remaining(session)[0];}
export function navigate(session,delta){const r=remaining(session);if(!r.length)return;const i=r.findIndex(e=>e.id===session.current);session.current=r[(Math.max(0,i)+delta+r.length)%r.length].id;}
export function completeEntry(session,id){const entry=session.entries.find(e=>e.id===id);if(!entry||entry.completed)return false;const r=remaining(session),i=r.findIndex(e=>e.id===id);entry.completed=true;entry.completedAt=new Date().toISOString();session.current=r.length>1?r[(i+1)%r.length].id:null;return true;}
export function archiveWeek(state){state.active.archivedAt=new Date().toISOString();state.archives.push(state.active);state.active=createWeek(state.active.number+1,state.settings);state.view={page:'home',day:null};}
export function previousResult(state,day,entry){const weeks=[...state.archives,state.active].reverse();for(const w of weeks){const order=[day,...DAYS.filter(d=>d!==day)];for(const d of order){const found=[...w.days[d].entries].reverse().find(e=>e.id===entry.id&&e.completed&&(e.weight!==null||e.reps!==null)&&e.variant===entry.variant&&e.unit===entry.unit);if(found)return {...found,day:d,date:found.completedAt,week:w.number};}}return state.seed.find(e=>e.id===entry.id&&e.variant===entry.variant&&e.unit===entry.unit)||null;}
export function validateState(s){
 const fail=()=>{throw new Error('This file is not a compatible Training backup. Nothing was changed.');};
 if(!s||s.schema!==1||!Number.isInteger(s.revision)||s.revision<0||!Array.isArray(s.archives)||s.archives.length>5000||!Array.isArray(s.seed)||s.seed.length>1000||!s.settings||typeof s.settings!=='object')fail();
 const str=(x,n=250)=>typeof x==='string'&&x.length<=n; const number=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0&&x<=10000; const ids=new Set();
 for(const w of [...s.archives,s.active]){if(!w||!str(w.id)||ids.has(w.id)||!Number.isInteger(w.number)||w.number<1||typeof w.bonus!=='boolean'||!w.days)fail();ids.add(w.id);for(const d of DAYS){const ses=w.days[d];if(!ses||!Array.isArray(ses.entries)||ses.entries.length!==ROUTINES[d].length)fail();const seen=new Set();for(const e of ses.entries){if(!e||!ROUTINES[d].some(x=>x.id===e.id)||seen.has(e.id)||!str(e.name)||!(e.variants===null||Array.isArray(e.variants)&&e.variants.length<=20&&e.variants.every(v=>str(v)))||!(e.completedAt===null||str(e.completedAt))||!str(e.target)||!str(e.unit)||typeof e.completed!=='boolean'||!number(e.sets)||!(e.weight===null||number(e.weight))||!(e.reps===null||Number.isInteger(e.reps)&&e.reps>=0&&e.reps<=1000)||![null,'more','right','hard'].includes(e.effort)||!(e.increment===null||number(e.increment)&&e.increment>0)||!(e.variant===null||str(e.variant))||!['exact','estimated'].includes(e.precision))fail();seen.add(e.id);}if(!(ses.current===null||seen.has(ses.current)))fail();}}
 for(const e of s.seed){if(!e||!DAYS.includes(e.day)||!str(e.id)||!number(e.weight)||!Number.isInteger(e.reps)||!str(e.unit)||!['exact','estimated'].includes(e.precision))fail();}
 for(const [key,v] of Object.entries(s.settings)){if(!DAYS.some(d=>ROUTINES[d].some(e=>key===d+':'+e.id))||!v||!str(v.unit)||!number(v.increment)||v.increment<=0||Object.keys(v).some(k=>!['unit','increment'].includes(k)))fail();}
 if(!s.view||!['home','day','history','backup','review'].includes(s.view.page)||!(s.view.day===null||DAYS.includes(s.view.day)))fail();
 return s;
}
export function toCSV(s){const rows=[['Week','Day','Exercise','Variant','Sets','Target reps','Completed','Weight kg','Weight unit','Weight precision','Reps','Effort','Date','Source','Sets source']];for(const w of [...s.archives,s.active])for(const d of DAYS)for(const e of w.days[d].entries)rows.push([w.number,d,e.name,e.variant,e.sets,e.target,e.completed,e.weight,e.unit,e.precision,e.reps,e.effort,e.completedAt,'app','routine']);for(const e of s.seed)rows.push(['Historical',e.day,e.id,e.variant,e.sets,'',true,e.weight,e.unit,e.precision,e.reps,e.effort,e.date,e.source,e.sets_source]);return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
