import test from 'node:test';
import assert from 'node:assert/strict';
import {DAYS,initialState,remaining,currentEntry,navigate,completeEntry,archiveWeek,previousResult,validateState,toCSV} from '../dist/model.js';
test('routine counts and removed exercises match handover',()=>{const s=initialState();assert.deepEqual(DAYS.map(d=>s.active.days[d].entries.length),[8,8,4,7,6]);assert(!JSON.stringify(s.active).includes('Wrist Curls'));});
test('swiping wraps, preserves drafts and does not change remaining',()=>{const s=initialState(),day=s.active.days.Push;day.entries[0].weight=80;navigate(day,-1);assert.equal(currentEntry(day).id,'pushdown');navigate(day,1);assert.equal(currentEntry(day).weight,80);assert.equal(remaining(day).length,8);});
test('Done keeps the same card, preserves optional null logs and remains browsable',()=>{
 const s=initialState(),day=s.active.days.Push;completeEntry(day,'bench');assert.equal(currentEntry(day).id,'bench');assert.equal(currentEntry(day).completed,true);
 navigate(day,1);assert.equal(currentEntry(day).id,'incline-db');navigate(day,-1);assert.equal(currentEntry(day).id,'bench');
 assert.deepEqual([day.entries[0].weight,day.entries[0].reps,day.entries[0].effort],[null,null,null]);assert.equal(completeEntry(day,'bench'),false);assert.equal(remaining(day).length,7);
});
test('completion counts stay independent of browsing, including an entirely completed deck',()=>{
 const s=initialState(),d=s.active.days.Push;for(const e of d.entries.slice(0,5))completeEntry(d,e.id);
 const seen=new Set();for(let i=0;i<16;i++){navigate(d,1);seen.add(currentEntry(d).id);assert.equal(remaining(d).length,3);}assert.equal(seen.size,8);
 for(const e of remaining(d))completeEntry(d,e.id);assert.equal(remaining(d).length,0);assert(currentEntry(d).completed);const before=d.current;for(let i=0;i<8;i++)navigate(d,1);assert.equal(d.current,before);
});
test('new week snapshots incomplete drafts and retains original templates',()=>{const s=initialState();s.active.days.Push.entries[0].weight=87.5;s.active.days.Push.entries[0].variant='Alternate bench';completeEntry(s.active.days.Pull,'face-pull');s.settings['Push:bench']={unit:'total weight',increment:2.5};archiveWeek(s);assert.equal(s.active.number,2);assert.equal(s.archives[0].days.Push.entries[0].weight,87.5);assert.equal(s.archives[0].days.Pull.entries[3].completed,true);assert.equal(s.active.days.Push.entries[0].weight,null);assert.equal(s.active.days.Push.entries[0].variant,null);assert.equal(s.active.days.Push.entries[0].increment,2.5);s.active.days.Push.entries[0].name='Changed';assert.equal(s.archives[0].days.Push.entries[0].name,'Bench Press');});
test('historical precision, corrected weights and high reps preserved',()=>{const s=initialState();assert.equal(previousResult(s,'Push',s.active.days.Push.entries[1]).reps,12);assert.equal(previousResult(s,'Push',s.active.days.Push.entries[4]).reps,11);assert.equal(previousResult(s,'Pull',s.active.days.Pull.entries[1]).precision,'estimated');assert.equal(previousResult(s,'Pull',s.active.days.Pull.entries[3]).weight,23.7);assert.equal(previousResult(s,'Upper',s.active.days.Upper.entries[1]).day,'Push');});
test('unlogged completion does not displace actual history',()=>{const s=initialState();completeEntry(s.active.days.Push,'bench');archiveWeek(s);assert.equal(previousResult(s,'Push',s.active.days.Push.entries[0]).weight,80);});
test('full JSON backup round trips drafts, current card, history and units',()=>{const s=initialState();s.active.days.Push.entries[1].weight=30;s.active.days.Push.entries[1].reps=9;navigate(s.active.days.Push,1);s.active.bonus=true;archiveWeek(s);const copy=validateState(JSON.parse(JSON.stringify(s)));assert.deepEqual(copy,s);assert(toCSV(s).includes('routine_inferred'));});
test('malformed backup rejected without modifying state',()=>{const s=initialState(),bad=structuredClone(s);bad.active.days.Push.entries[0].weight='bad';assert.throws(()=>validateState(bad),/compatible/);assert.equal(s.active.days.Push.entries[0].weight,null);assert.throws(()=>validateState({schema:2}));});
