require('node:fs').mkdirSync('test-artifacts',{recursive:true});
﻿const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:process.env.BROWSER_CHANNEL||undefined,headless:true});try{const p=await b.newPage({viewport:{width:375,height:667},isMobile:true,hasTouch:true});await p.goto(process.env.APP_URL||'http://127.0.0.1:5173');await p.locator('.day-symbol').first().waitFor();
const boxes=await p.locator('.day-symbol').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('path').getBBox();return [r.width,r.height,b.width,b.height]}));for(const box of boxes)assert.deepEqual(box,[32,32,16,16]);
await p.locator('[data-action=bonus]').click();await p.locator('.bonus.complete').waitFor();assert.deepEqual(await p.locator('.bonus .day-symbol').evaluate(e=>{const b=e.querySelector('path').getBBox();return [b.width,b.height]}),[16,16]);
for(const day of ['Push','Pull','Legs','Upper','Lower']){await p.locator('[data-day='+day+']').click();await p.locator('.is-front').waitFor();const original=await p.locator('.is-front').getAttribute('data-entry');await p.getByRole('button',{name:'Done',exact:true}).click();await p.locator('.is-front.is-complete').waitFor();await p.getByRole('button',{name:'All exercises',exact:true}).click();await p.locator('.mini-card').first().waitFor();const count=await p.locator('.mini-card').count();assert.equal(count,{Push:8,Pull:8,Legs:5,Upper:7,Lower:6}[day]);assert.equal(await p.locator('.mini-card.is-complete').count(),1);assert.equal(await p.locator('.mini-card.is-complete').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(24, 62, 48)');assert.equal(await p.locator('.mini-card:not(.is-complete)').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(32, 31, 39)');assert.equal(await p.locator('.card-stack').count(),0);
for(const size of [{width:375,height:667},{width:390,height:664},{width:390,height:844}]){await p.setViewportSize(size);assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight),size.height);const close=await p.getByRole('button',{name:'Close',exact:true}).boundingBox();assert(close.y+close.height<=size.height);}
await p.getByRole('button',{name:'Close',exact:true}).click();await p.locator('.is-front').waitFor();assert.equal(await p.locator('.is-front').getAttribute('data-entry'),original);
await p.getByRole('button',{name:'All exercises',exact:true}).click();const target=await p.locator('.mini-card').last().getAttribute('data-id');await p.locator('.mini-card').last().click();await p.waitForFunction(id=>document.querySelector('.is-front')?.dataset.entry===id,target);assert.equal(await p.locator('#remaining-count').innerText(),(count-1)+' of '+count+' remaining');await p.reload();await p.waitForFunction(id=>document.querySelector('.is-front')?.dataset.entry===id,target);await p.locator('.back').click();}
await p.locator('[data-day=Push]').waitFor();await p.screenshot({path:'test-artifacts/overview-home.png'});await p.locator('[data-day=Push]').click();await p.getByRole('button',{name:'All exercises',exact:true}).click();await p.screenshot({path:'test-artifacts/overview-grid.png'});console.log('PASS: uniform icon bounds including tick; all five overviews, colors/completion, Close position, selection persistence and three phone layouts');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
